// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
"use client";
import "@/assets/scss/main.scss";
// export const metadata = {
//   title: "Profile",
//   // description: "Generated by create next app",
// };
import { SessionProvider } from "next-auth/react";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
